### PR TITLE
feat: emit current folder and fix update type

### LINKED ISSUE #71: "Select current folder" not possible with hidden Select button
When using external buttons to confirm the selection, the consumer of the file picker widget relies on `update` events to track the current selection. In `location` mode, the event fired after entering a new folder does not include any entries. This makes it impossible to select the current folder, like the internal button allows to.

To solve this, either a separate event for navigation is required, or the `update` event in `location` mode needs to include the current folder when nothing else is selected.

Also, when issue #8 is implemented, the navigation/update event will need to be fired on initial load to communicate the actual permissions of the starting folder, i.e. whether the user is allowed to upload files there. If the root folder can have restricted permissions, then an initial event is already required now.

### PR DESCRIPTION
**Pull request by LukasHirt**
When loading new folder in Location picker, we are emitting an "update" with the current route as an argument. We've fixed that the argument has type array now so that it is consistent with all other arguments returned in the `update` event. We've also added event called `folderLoaded` that is emitted every time a loading of any folder has ended.
It is emitting the current folder as an argument.

Fixes #71

### CODE REVIEW

File: src/main.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ new Vue({
   render: (h) => {
     return h(App, {
       props: {
-        variation: 'resource',
+        variation: 'location',
```
Comment (kulmann) [inline src/main.js:8]: Leftover from dev or did you change the default intentionally?

Comment (LukasHirt) [reply src/main.js:8]: Yep, leftover. Will roll it back

Comment (LukasHirt) [reply src/main.js]: Done

**Comment by LukasHirt** [comment]
As it was only a change of one word I did a rebase. It shouldn't make the review harder

**Review by kulmann — APPROVED** [review]
Nice! 👍
